"""add items_json to briefs

Revision ID: ca0d6e3b015f
Revises: 92275b8899e2
Create Date: 2026-09-18 15:49:02.847883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0d6e3b015f'
down_revision: Union[str, Sequence[str], None] = '92275b8899e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefs', sa.Column('items_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('briefs', 'items_json')
    # ### end Alembic commands ###
